### ISSUE TITLE
很棒的例子，也遇到了相同的问题 想问下 【产生问题的原因】

### ISSUE THREAD

**Issue by imzyf** [wiiale/NavgationTitlePoppingDemo#1]
看了 blog

> 或响应布局而调用的任何其他方法都可能导致布局循环。布局更改调用的viewWillAppear似乎触发了所提到的布局循环。

问题产生的原因没太明白，能在解释下吗？

我还发现 侧滑 的时候不会有 title 被影响，但是点击 back 按钮返回，title 会被子 ctrl 影响，这是为什么呢？

还有其他的解决方案吗？

感谢

**Comment by wiiale** [comment]
>In iOS 10, UIKit has updated and unified background management for UINavigationBar, UITabBar, and UIToolbar. In particular, changes to background properties of these views (such as background or shadow images, or setting the bar style) may kick off a layout pass for the bar to resolve the new background appearance.
>In particular, this means that attempts to change the background appearance of these bars inside of layoutSubviews, -[UIView updateConstraints], viewWillLayoutSubviews, viewDidLayoutSubviews, updateViewConstraints, or any other method that is called in response to layout may result in a layout loop.
>
>In some cases you can break these layout loops by ensuring that you always use the same object instance when objects (such as UIImage or UIColor) are required. But in general you should avoid doing this.
>
>Because all appearance parameters are now resolved at one time, there may be some cases where your bar's appearance has changed. In general, best results are obtained by specifying as little as possible for customizing your bar. For example, if you are specifying a barTintColor value and specifying an empty UIImage object for the backgroundImage property (as is the case when you call [UIImage new], for example) then you should get better results by specifying only the barTintColor. Any changes you make to resolve these issues in iOS 10 should also work correctly in iOS 9—if this is not the case, please report bugs with a sample project and a screenshot indicating what the bars should look like.

原因是参考 [iOS SDK Release Notes for iOS 10.0](https://developer.apple.com/library/archive/releasenotes/General/RN-iOSSDK-10.0/index.html#//apple_ref/doc/uid/TP40017540-CH1-SW1) 猜测的，也许点击返回触发了布局循环，测试过这个问题不存在 iOS 9 中。解决方法原理是修改设置 UI 的时机，从侧面验证这个猜测哈。

其他的解决办法是拓展 UINavigationController 和 UIViewController，在本仓库的 swizzle 分支可以找到。本质上也是修改更新 UI 的时机。这个方式比较容易配合项目自定义 NavigationBar。
